create user 'anonimo'@'localhost' identified with mysql_native_password by 'anonimo';
GRANT Anonimo to 'anonimo'@'localhost';
create user 'cliente'@'localhost' identified with mysql_native_password by 'cliente';
GRANT Cliente to 'cliente'@'localhost';
create user 'CLVKVN89Y7471'@'localhost' identified with mysql_native_password by 'kevin007';
GRANT Cliente to 'CLVKVN89Y7471'@'localhost';
create user 'COCLUS17R289W'@'localhost' identified with mysql_native_password by 'luisa000';
GRANT Cliente to 'COCLUS17R289W'@'localhost';
create user 'GHLDNL34R57AE'@'localhost' identified with mysql_native_password by 'daniela111';
GRANT Cliente to 'GHLDNL34R57AE'@'localhost';
create user 'LYTCRL23J563L'@'localhost' identified with mysql_native_password by 'carlo000';
GRANT Cliente to 'LYTCRL23J563L'@'localhost';
create user 'PMPMRC99M200R'@'localhost' identified with mysql_native_password by 'marco345';
GRANT Cliente to 'PMPMRC99M200R'@'localhost';
create user 'QPTJSN38T077R'@'localhost' identified with mysql_native_password by 'jason337';
GRANT Cliente to 'QPTJSN38T077R'@'localhost';
create user 'RRNGRG78S10E'@'localhost' identified with mysql_native_password by 'giorgia77';
GRANT Cliente to 'RRNGRG78S10E'@'localhost';
create user 'SCHFRN23F452M'@'localhost' identified with mysql_native_password by 'francesca123';
GRANT Cliente to 'SCHFRN23F452M'@'localhost';
create user 'SZCHMR91E578E'@'localhost' identified with mysql_native_password by 'homer86';
GRANT Cliente to 'SZCHMR91E578E'@'localhost';
create user 'TNTBOB83Y24DP'@'localhost' identified with mysql_native_password by 'bob010';
GRANT Cliente to 'TNTBOB83Y24DP'@'localhost';
create user 'VRLNOA12D345G'@'localhost' identified with mysql_native_password by 'noa554';
GRANT Cliente to 'VRLNOA12D345G'@'localhost';
create user 'operatore'@'localhost' identified with mysql_native_password by 'operatore';
GRANT Operatore to 'operatore'@'localhost';
create user 'BRTIRS35O8991'@'localhost' identified with mysql_native_password by 'iris678';
GRANT Operatore to 'BRTIRS35O8991'@'localhost';
create user 'LDRALC78T098B'@'localhost' identified with mysql_native_password by 'alice558';
GRANT Operatore to 'LDRALC78T098B'@'localhost';
create user 'MRREMM89Q345L'@'localhost' identified with mysql_native_password by 'emma333';
GRANT Operatore to 'MRREMM89Q345L'@'localhost';
create user 'MTTUGO94D598U'@'localhost' identified with mysql_native_password by 'ugo997';
GRANT Operatore to 'MTTUGO94D598U'@'localhost';
create user 'TWSLVR18L50R'@'localhost' identified with mysql_native_password by 'oliver006';
GRANT Operatore to 'TWSLVR18L50R'@'localhost';